### ISSUE TITLE
Caching file, returning disk URL to retrieve later

### ISSUE THREAD

**Issue by jamescmartinez** [Haneke/HanekeSwift#101]
Hey there!

I have a requirement to cache video data, but then retrieve the URL location for that data. The reason for this is an `AVAsset` cannot be created using `NSData`, only via a URL. 

A very hacky (and very unreliable) way to do it now via Haneke is to do the following:

```
let cache = Haneke.sharedDataCache
cache.fetch(URL: URL).onSuccess { (data) in
  // Hacky way of getting cache URL from Haneke
  let path = DiskCache(name: "shared-data", capacity: UINT64_MAX).pathForKey(URL.absoluteString!)
  let cacheURL = NSURL(fileURLWithPath: path)
}
```

What are your thoughts on how this should be handled? Should I forego using Haneke for this specific feature and build a disk-only cache instead?

James

**Comment by switz** [comment]
+1 same problem

Would love to see a clearer API or example for creating `memory://` based NSURLs. I'll share whatever I come up with.

**Comment by dcunited001** [comment]
i'm running into this problem as well.  EZAudio uses ExtAudio for file access and there's no way to get around it.  

for now, i'm just going to read out of Haneke's disk cache, but create a temporary file with the NSData that's returned.  that way i can easy clear out the temp files whenever i want, like on app restart or whatever. and basically my app can throw away those temp files at any time.  but i can still cache the audio i'm retrieving from the net.

not the best solution, but it works for what i need right now.

**Comment by frangeris** [comment]
I have the same issue, just for future references if somebody stuck with this, here my workaround (I'm reusing the player of [SCRecorder](https://github.com/rFlex/SCRecorder))

```swift
let cache = Shared.dataCache
let URL = NSURL(string: "<video url>")!

cache.fetch(URL: URL).onSuccess { stream in

    let path = NSURL(string: DiskCache.basePath())!.URLByAppendingPathComponent("shared-data/original")
    let cached = DiskCache(path: path.absoluteString).pathForKey(URL.absoluteString)
    let file = NSURL(fileURLWithPath: cached)

    // so lets play the video
    let player: SCPlayer = SCPlayer()
    player.setItemByUrl(file)
    let layer = AVPlayerLayer(player: player)
    layer.frame = self.viewer.bounds
    self.viewer.layer.addSublayer(layer) // this is my view
    player.play()
}
```

Thank's @jamescmartinez for show the way...

**Comment by jpincheira** [comment]
thanks @frangeris, works perfect!

**Comment by alimertturker** [comment]
@frangeris  Hi I have tried to implement your way in uitableview but when I scroll fast I can not watch the cached data.

**Comment by frangeris** [comment]
@alimertturker More details, maybe we can help you.

PS: have in mind that resources loaded for cell in table view could crash cuz index change and cells are reusable while you scroll...

**Comment by alimertturker** [comment]
Actually I am trying to build an app like vine. I have two Player in my class and I am adding them with respect to its number for example if row is odd I am adding player 1 otherwise player 2. I ve tried to implement your code in tableview cellforrowat indexpath but when I scroll so fast after some point players can not load and it causes a lag. Now I am using a temporary basic solution  

cache.fetch(URL: URL).onSuccess { stream in

    let path = NSURL(string: DiskCache.basePath())!.URLByAppendingPathComponent("shared-data/original")
    let cached = DiskCache(path: path.absoluteString).pathForKey(URL.absoluteString)
    let file = NSURL(fileURLWithPath: cached)
} 

I m using only this part, then put file into dictionary with my video id. It s okey for right now but I do not understand why I can 't use in your way. Also my solution is lagging a little bit. I need more advance advises for caching video.

**Comment by patthehuman** [comment]
@frangeris thanks for the snippet. Question: Is there a way to get it working with AVPlayer?

**Comment by frangeris** [comment]
@patthehuman Haneke give you NSData object, AVPlayer needs an [NSURL](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVPlayer_Class/#//apple_ref/occ/instm/AVPlayer/initWithURL:) or [AVPlayerItem](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVPlayer_Class/#//apple_ref/occ/instm/AVPlayer/initWithPlayerItem:) object, that snippet is the only way I was able to... if you find another possible way, please share it here...

**Comment by patthehuman** [comment]
@frangeris i see.... very interesting. I looked further into the issue and i noticed that the FIRST time you cal the cache onSuccess, it wont show up. if you call it again, however, it will show up. I made it so if the cache file doesnt exists, write the NSData to it, and read that. The in the future, the file will exist, and work fine



                        let URL = NSURL(string: location)!
                        
                
                        self.cache.fetch(URL: URL).onSuccess { stream in    

                            let path = NSURL(string: DiskCache.basePath())!.URLByAppendingPathComponent("shared-data/original")
                            let cached = DiskCache(path: path.absoluteString).pathForKey(URL.absoluteString)
                            let file = NSURL(fileURLWithPath: cached)
                            
                            //if there is no file, write it so it can be used in the player.
                            if !NSFileManager.defaultManager().fileExistsAtPath(cached) {
                                try! stream.writeToFile(cached, options: NSDataWritingOptions.AtomicWrite)
                            }
                            
                            
                            
                            self.player = AVPlayer(URL: file)

                            let playerLayer = AVPlayerLayer(player: self.player)
                            playerLayer.frame = self.view.bounds
                            cell.videoView.layer.addSublayer(playerLayer)

                            self.player.play()
                         
                        }

**Comment by X901** [comment]
@frangeris Thank you very much , but I noticed sometime it play the audio from internet not from cache I don't know why , but must time it play it from cache

**Comment by X901** [comment]
@patthehuman you solved my problem 

I convert your code to **Swift 3** syntax 

Thank you @patthehuman and @frangeris 

```
 let cache = Shared.dataCache
let url = URL(string: location)!

cache.fetch(URL: url).onSuccess { stream in
                
 let path = NSURL(string: DiskCache.basePath())!.appendingPathComponent("shared-data/original")
let cached = DiskCache(path: (path?.absoluteString)!).path(forKey: url.absoluteString)
 let file = NSURL(fileURLWithPath: cached)
                
 url = file as URL!

//if there is no file, write it so it can be used in the player.
if !FileManager.default.fileExists(atPath: cached) {
try! stream.write(to: URL(string : cached)! , options: NSData.WritingOptions.atomicWrite)
         
                }
            }

```

**Comment by giusecapo** [comment]
Hi guys, I tryied to do like @X901 but AVPlayer remains empty (not loading videos). If I check file existence, there is. But still, no video is displayed. Why this?
