### ISSUE TITLE
Support iOS7

### ISSUE THREAD

**Issue by jmacmullin** [Haneke/HanekeSwift#111]
Swift apps can run on iOS7. It'd be nice if I could still use HanekeSwift on iOS7 too. Obviously iOS7 doesn't support frameworks so including Haneke in my app won't be as simple, but is there any reason Haneke wouldn't work on iOS7? Or you using (or planning to use) iOS8 specific APIs?

**Comment by AvdLee** [comment]
Any news on this? I'm thinking to implemented HanekeSwift instead of SDWebImage, but I need iOS 7 support for this.

**Comment by eyeballz** [comment]
you can use my fork which works for iOS7
i don't think Haneke Swift will officially support iOS7 since there are a lot of drawbacks.

**Comment by fabdarice** [comment]
Hi @eyeballz 
I've used your fork to copy the Haneke folder into my project and I'm having this error that affects a lot of my files :
"'JSON' is ambiguous for type lookup in his context".
Do you have any idea why and how to fix it? 
Very much appreciate thanks

**Comment by eyeballz** [comment]
Hey @fabdarice ,
since you are using ios 7 there is no namespacing. That means all your classes live in one big namespace. My guess is that you have another class from another library named JSON aswell and that it is conflicting.

**Comment by fabdarice** [comment]
Thanks @eyeballz .
Indeed I'm was using SwiftJSON which has a JSON struct too.
I end up renamed all JSON to JSON_SWIFTY and it solves the problems. Thanks a lot!

**Comment by dwoshadha** [comment]
Hi @eyeballz ,
I was working on this and it worked perfectly. After the xcode 6.3 with swift 1.2 release it give me errors. Could you please help me on this? Thanks a lot.

**Comment by thomascsorbamedia** [comment]
@dwoshadha, try comparing your version of Haneke with the original code and replace the functions that are giving errors for most of the errors this will solve it. The only error that remains for me is in this function and i can't seem to figure it out. Maybe someone can have a look?

public init(name : String) {
        self.name = name
        
        let notifications = NSNotificationCenter.defaultCenter()
        // Using block-based observer to avoid subclassing NSObject
        memoryWarningObserver = notifications.addObserverForName(UIApplicationDidReceiveMemoryWarningNotification,
            object: nil,
            queue: NSOperationQueue.mainQueue(),
            usingBlock: { [unowned self] (notification : NSNotification!) -> Void in
                self.onMemoryWarning()
            }
        )
        
        var originalFormat = HNKFormat<T>(name: HanekeGlobals.Cache.OriginalFormatName)
        self.addFormat(originalFormat)
    }

**Comment by oshadha** [comment]
@eyeballz is there a way that I can show a default image while it loads the actual. Do we have a default function for that?

**Comment by oshadha** [comment]
@eyeballz I converted the Haneke iOS7 to work with xCode 6.4 and Swift 1.2. I wanna push it. Please let me know how can I do that.

**Comment by seenickcode** [comment]
@eyeballz , any update on this or what @oshadha has done?  Thanks.

**Comment by oshadha** [comment]
Hi @seenickcode , Please let me know if you wanna have Swift 1.2 converted code.

**Comment by seenickcode** [comment]
Yes please!

**Comment by eyeballz** [comment]
Hey, you can also make a pull request here https://github.com/eyeballz/HanekeSwift
then i will accept it

**Comment by oshadha** [comment]
@seenickcode just drop me a mail. oshadha@gmail.com

**Comment by oshadha** [comment]
hi @eyeballz , When I try to sync it give me following error:
fatal: unable to access 'https://github.com/eyeballz/HanekeSwift.git/': Empty reply from server
 (128)

Please advise me.

**Comment by eyeballz** [comment]
Just fork it and then commit the changes there. dont even have to create a pull request then

**Comment by oshadha** [comment]
I was trying to upload my Swift 1.2 changes as new branch and it keeps me saying that "Authentication Failed"

**Comment by hpique** [comment]
Closing this as it's less and less likely that new people will find it helpful.
