### ISSUE TITLE
Fetch with custom headers

### ISSUE THREAD

**Issue by natpicone** [Haneke/HanekeSwift#128]
Hi,
my auth schema requires to send out some custom headers while fetching images and json.
Which is the best way to add this ?

Thanks a lot,
Cheers

**Comment by hpique** [comment]
@jimmyhillis Yep. That's exactly why the session is public. :)

**Comment by alezoffoli** [comment]
I've referenced to #128 to create a fetch with custom headers.

But whenever I declare

public class CustomNetworkFetcher : NetworkFetcher {

}

I get:
![screen shot 2015-05-28 at 11 10 14 am](https://cloud.githubusercontent.com/assets/5590195/7862108/52132ce4-052a-11e5-86e4-de34abe387a6.png)

Any ideas?
