### ISSUE TITLE
json cache question

### ISSUE THREAD

**Issue by kolisko** [Haneke/HanekeSwift#131]
Hi, I would like to ask you if is possible to use Haneke to cache remote json file by calling fetch from url method, then kill the app, run app again without network access and call the fetch from url again to get it from local cache automatically? If so how can I do that pls? 

Example in readme.md shows how to fetch it from url and manage json data in onSuccess method only.

Thank you, Michal

EDIT: Solved!

**Comment by hpique** [comment]
I might be missing something but that's exactly what fetch does. If you don't need the data when you call fetch, then simply don't provide a success block.

**Comment by kolisko** [comment]
Hi hpique, thank you for answer. I need the data when call fetch. But when network will be not available I think onSuccess block will not be called, is it right? Then I can not access cached (previously downloaded) file using this method or can I?

**Comment by dcharbonnier** [comment]
the comment say solved
