### ISSUE TITLE
How do you subclass Fetcher?

### ISSUE THREAD

**Issue by djtarazona** [Haneke/HanekeSwift#138]
I'm trying to subclass `Fetcher<T>` but it appears to have no public initializers.

The compiler is telling me
`cannot be constructed because it has no accessible initializers` when I try to instantiate my custom fetcher class.

```swift
class CustomFetcher<T: DataConvertible>: Fetcher<T> {}

let fetcher = CustomFetcher<UIImage>(key: "test") // cannot be constructed because it has no accessible initializers
```

When I try to add my own initializer and call `super.init()` (as required by Swift), I get the message `Fetcher<T> does not have a member named 'init'`

```swift
class CustomFetcher<T: DataConvertible>: Fetcher<T> {
    init(key: String) {
        super.init(key: key) // Fetcher<T> does not have a member named 'init'
    }
}

let fetcher = CustomFetcher<UIImage>(key: "test")
```

**Comment by preble** [comment]
I ran into this too. Thankfully #224 made the initializer and methods on Fetcher public.
