### ISSUE TITLE
Prefetching/preloading images to disk

### ISSUE THREAD

**Issue by hjalmarsn** [Haneke/HanekeSwift#140]
Love Haneke and use it in many applications. Although, it would be nice if you could prefetch URLs/images to the diskCache eg for offline use further on.

The problem is that if you call:
 cache.fetch(URL: queueImageDownloads[0], success:{ image in
                println("Success!")
            })

You quickly run into memory warnings. What's the best way to prefetch to disk using Haneke?

**Comment by hpique** [comment]
Memory warnings are not necessarily bad. The memory cache will be emptied and that's it. Care to elaborate?

You could always bypass the memory cache and use DiskCache directly. I guess we could also add an option to skip the memory cache to make this simpler.

**Comment by sebbean** [comment]
I would also utilize this feature. Are formats the only way to enable disk cache?

I'm hoping to pre-cache all images in the background when the first API response is received.
