### ISSUE TITLE
Question: Download from S3 bucket with non public ACL

### ISSUE THREAD

**Issue by yourdeveloper** [Haneke/HanekeSwift#141]
Is it possible to use haneke to download an image from a non public S3 URL by reading the configuration from S3 like you would normally do with the AWS SDK

 var transferManager: AWSS3TransferManager = AWSS3TransferManager.defaultS3TransferManager()
        var uploadRequest: AWSS3TransferManagerUploadRequest = AWSS3TransferManagerUploadRequest()

**Comment by hpique** [comment]
You will have to implement your own fetcher. They're extensible to support use cases like this. Check out the source and if you hit any roadblocks, feel free to open another issue.
