### ISSUE TITLE
Convenience method for fetching UIImage with completion blocks.

### ISSUE THREAD

**Issue by coylums** [Haneke/HanekeSwift#144]
I see the potential for a use case for fetching and caching a UIImage with success/failure blocks without the need for UIImageView. I'm working on this now and can submit a pull request if this could be added to the project?

Thanks!

**Comment by hpique** [comment]
Why not use fetch on Cache?

**Comment by coylums** [comment]
Fetch on Cache worked successfully.  I added and will be using a convenience method on UIIMage, I can submit a pull request if you'd like to review/merge?
