### ISSUE TITLE
Back in February

### ISSUE THREAD

**Issue by hpique** [Haneke/HanekeSwift#146]
Heya. I haven't been able to work in this project lately, mostly due to the holidays and now vacation. I should be back to actively contributing in early February.

If you're comfortable with Haneke, I would greatly appreciate if you can respond to issues and help fellow Haneke users.

**Comment by joanromano** [comment]
Hey there! I've been also out due basically to vacation and the hard launch of the project I work for. I'd love to get back to HanekSwift in February as well.
