### ISSUE TITLE
Haneke with SwiftyJSON: 'JSON' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by attheodo** [Haneke/HanekeSwift#147]
Hello, I am working on a project that includes both SwiftyJSON and Haneke as Pods from Cocoapods. I import SwiftyJSON and HanekeSwift in my AppDelegate. However I am getting ` 'JSON' is ambiguous for type lookup in this context` in this line statement `var chatChannels: Array<JSON>?`. Same thing applies if I try to only include HanekeSwift in a UITableViewCell subclass where I need to load some images from the cache. 

Any ideas?

**Comment by attheodo** [comment]
I temporarily fixed this by commenting out all JSON related formats from of Haneke. Anything less ugly?

**Comment by Garnel** [comment]
I use Haneke instead... Seems that you use HanekeSwift only to load image, Haneke is enough

**Comment by attheodo** [comment]
@Garnel this answer is not really constructive.

Anyway, I figured the proper way to resolve this. I needed to explicitly declare the framework from which the Type I wanted to use. In that case that'd be `var chatChannels: Array<Alamofire.JSON>?`

**Comment by Garnel** [comment]
@attheodo Sorry, I used to use HanekeSwift in a project targeting iOS7, you know iOS7 has no frameworks, It's impossible to place SwiftJSON and HanekeSwift together. So I turn back to Haneke instead, and it just works.

Seems your solution do it more `swiftly`

**Comment by HerbstLukas** [comment]
I have the same issue :/ 
Any way to use this two awesome projects together?

**Comment by HerbstLukas** [comment]
@attheodo Thanks for this tip! Worked perfekt! <3

**Comment by leversol** [comment]
You are right Garnel. Thanks!

**Comment by kaushikdas0** [comment]
Just use 
var urVariable = SwiftyJSON.JSON(someObject!)

Referring to SwiftyJSON directly will solve the issue.

**Comment by hpique** [comment]
What @kaushikdas0 said. Swift libraries are bound to have name conflicts. Just be explicit about the type and or use typealias.

**Comment by tirrorex** [comment]
Why don't you integrate directly swiftyJSON (which is massively used, even by alamofire) instead of doing your thing and declaring the same type?

The example of this bug i had today was a controller calling my imageCache, and this controller also has a callback which is expected to receive a JSON as paramter.

I managed to get around the issue but depending on the code it could become ugly quickly
