### ISSUE TITLE
Swift 1.2 compile issues

### ISSUE THREAD

**Issue by SteveNewhouse** [Haneke/HanekeSwift#151]
Lots of compile issues with Swift 1.2 (not unique to this library, FWIW).  Tried the auto-convert to 1.2 and that did not resolve them all.

Tried fixing other manually but not familiar enough with the 1.2 migration issues to work through it.

**Comment by hpique** [comment]
Should have this fixed during the weekend. :)

**Comment by mikenolimits** [comment]
looking forward to this :) 

I tried to do the fixes myself and my brain exploded :'(

**Comment by bokzor** [comment]
Any news about this issue ?

**Comment by attheodo** [comment]
+1 for fixing this

**Comment by bokzor** [comment]
Anyway you can use the objective C version.....

**Comment by mikenolimits** [comment]
@bokzor it works?

**Comment by bokzor** [comment]
for sure. Juste put this in your bridging header : #import "Haneke.h"

And then you can call the function : imageView.hnk_setImageFromURL(url)

**Comment by mikenolimits** [comment]
@bokzor thanks :) I suppose that will do for now

**Comment by attheodo** [comment]
Nice, is this getting merged anytime soon?

**Comment by jmacmullin** [comment]
Oops, I wish I'd seen this thread before I had a go at this :-)

My attempt is here:
https://github.com/jmacmullin/HanekeSwift/commit/31b91ff1a069edf16191075e469b0650b8630802

I'd be interested to see how this differs from what other people have done. In particular, I wasn't sure the best way to handle the autoclosures that can escape. I've annotated them as @autoclosure(escaping) but perhaps some of these should be explicit closures instead to make the capture semantics clearer to calling code.

**Comment by kishinmanglani** [comment]
Any update on this?

**Comment by nobunobu** [comment]
I am looking for this for a while too...

**Comment by hpique** [comment]
Back in action. I expect to have the update ready today.
