### ISSUE TITLE
Shared.imageCache.removeAll() not working ?

### ISSUE THREAD

**Issue by ollydbgz** [Haneke/HanekeSwift#157]
I'm using Shared.imageCache.removeAll() to delete all memory&disk cache

But not working. Image should't show on UIImage because I'm delete that image from server.

Thank you.

**Comment by marcioadr88** [comment]
Doesn't worked for me too

**Comment by mckayryane** [comment]
+1

**Comment by dcharbonnier** [comment]
fixed with #267
