### ISSUE TITLE
Is there any way to check if an image has already cached? 

### ISSUE THREAD

**Issue by rosendi** [Haneke/HanekeSwift#158]
Hello! Is there any way to check if an image has already cached? For example: 

`Shared.imageCache.fetch(fetcher:).onSuccess { (image, wasInCache) in }`

I've just dived to source code but didn't find proper way....

**Comment by jbraun002** [comment]
This would be great - I'm searching for a way to test if the cache has an item but haven't found any call that does this (so far).

**Comment by rosendi** [comment]
@jbraun002 I don't remember all the details, but I achieved it in this way: 

```
import Haneke

class ActivityNetworkFetcher<T : DataConvertible> : NetworkFetcher<T> {
  private(set) var remote = false
  private(set) var fetching = false
  private(set) var canceled = false

  override init(URL: NSURL) {
    super.init(URL: URL)
  }
  
  override func fetch(failure fail : ((NSError?) -> Void), success succeed : (T.Result) -> Void) {
    remote = true
    fetching = true
    
    let activitySucceed: (T.Result) -> Void = { result in
      UIApplication.sharedApplication().hideNetworkActivityIndicator()
      self.fetching = false
      succeed(result)
    }
    
    let activityFail: (NSError?) -> Void = { error in
      UIApplication.sharedApplication().hideNetworkActivityIndicator()
      self.fetching = false
      fail(error)
    }
    
    UIApplication.sharedApplication().showNetworkActivityIndicator()

    super.fetch(failure: activityFail, success: activitySucceed)
  }
  
  override func cancelFetch() {
    if fetching {
      UIApplication.sharedApplication().hideNetworkActivityIndicator()
    }
    
    canceled = true
    
    super.cancelFetch()
  }
}
```

Example:

```
let fetcher = ActivityNetworkFetcher<UIImage>(URL: ...)

cache.fetch(fetcher: fetcher).onSuccess { image, remote in
  if (remote) ...
}
```

As I remember you can query the cache directly if you know a key:

```
Shared.imageCache.fetch(key: ...)
```

Sorry, it was a long time ago.

**Comment by silonab** [comment]
This is the solution I've found: 

`let cache = Shared.imageCache
        cache.fetch(key: url, formatName: HanekeGlobals.Cache.OriginalFormatName, failure: { (error) in
            // image does not exist, need to fetch from URL
            cache.fetch(URL: NSURL(string: url)!, formatName: HanekeGlobals.Cache.OriginalFormatName, failure: { (error) in
                print(error)
            }) { (image) in
                print(image)
                // save to cache
                cache.set(value: image, key: url, formatName: HanekeGlobals.Cache.OriginalFormatName, success: { (image) in
                    print(image)
                // post notification for image being ready
                })
            }
        }) { (image) in
                print("image exists")
        }`

**Comment by silonab** [comment]
This is the solution I've found:

```
let cache = Shared.imageCache
        cache.fetch(key: url, formatName: HanekeGlobals.Cache.OriginalFormatName, failure: { (error) in
            // image does not exist, need to fetch from URL
            print(error)
            cache.fetch(URL: NSURL(string: url)!, formatName: HanekeGlobals.Cache.OriginalFormatName, failure: { (error) in
                print(error)
            }) { (image) in
                print(image)
                // save to cache
                cache.set(value: image, key: url, formatName: HanekeGlobals.Cache.OriginalFormatName, success: { (image) in
                    print(image)
                // post notification for image being ready
                })
            }
        }) { (image) in
                print("image exists")
        }
```

**Comment by tirrorex** [comment]
Thanks for the tips mate, really helped me build my own solution 👍
