### ISSUE TITLE
hnk_setImageFromURL() cause app crash !!!

### ISSUE THREAD

**Issue by TheFlow95** [Haneke/HanekeSwift#163]
Hello,
I use your library to cache images and it works fine in simulator but when I launch my app by myself it crashes at start ! The problem is on this line:
```
imageView.hnk_setImageFromURL(post.thumbnailURL)
```
It's very urgent, can you help me ?
Thanks

PS: I'm in iOS 8.2

**Comment by mcdolejt** [comment]
I had the same issue.  It happened after updating to Xcode 6.2.  I was unable to figure out cause.

**Comment by TheFlow95** [comment]
Ok, I'm just idiot...
I didn't follow that step:
> Click on the + button at the top left of the panel and select New Copy Files Phase. Set Destination to Frameworks, and add Haneke.framework.

**Comment by djdance** [comment]
I have to to support 7.0 and can not build/add Haneke.framework, nor official instruction, it all fails.

I just dropped all swift files to my project. And it works. For last 2 months, on every device.
But now on old 7.0 it crashes (iOs8 still fine)

```
#12	0x001ad160 in UIImageView.hnk_setImageFromURL(NSURL, placeholder : UIImage?, format : Format<UIImage>?, failure : (NSError?) -> ()?, success : (UIImage) -> ()?) -> () at /Users/djdance/Documents/xxx/Haneke/UIImageView+Haneke.swift:21
```

here is

```
let fetcher = NetworkFetcher<UIImage>(URL: URL)
```
