### ISSUE TITLE
how do i prevent auto resize of images?

### ISSUE THREAD

**Issue by Joropo** [Haneke/HanekeSwift#167]
The haneke resizing function is distorting the aspect ratio of the images that are being placed in UICollectionview cells. How can i avoid/prevent/preset the condition for image resizing?

**Comment by hpique** [comment]
@Joropo Haneke will respect the `contentMode` of your `UIImageView`. It's probably set to `Fill`. Change it to `AspectFit` or `AspectFill` instead.

You can also use custom formats without resizing. Check the readme for more info.
