### ISSUE TITLE
How can I get the image in a synchronous way?

### ISSUE THREAD

**Issue by callmewhy** [Haneke/HanekeSwift#168]
Hi, I wonder how to get the image from disk in a synchronous way?    
Or maybe I should always load image in an asynchronous way?

**Comment by hpique** [comment]
@callmewhy Haneke only provides asynchronous APIs. However, you can convert any asynchronous API using GCD semaphores or groups, at the expense of blocking the main (or calling) thread. That is usually bad, which is why Haneke discourages it.
