### ISSUE TITLE
Status report

### ISSUE THREAD

**Issue by nickoneill** [Haneke/HanekeSwift#169]
If there isn't an update here before Swift 1.2 comes out, there's going to a be a ton of forks so that people like myself can continue shipping code with this.

What's the deal here? Plenty of promises have been made that this was going to be looked after "soon" since the new year. I understand people are busy and if you are let's find some others to help out with maintenance. Kicking the can isn't working and we're going to hit a wall with Swift 1.2 soon.

**Comment by akolov** [comment]
I second that and willing to help if you need manpower. Already had to create a fork with fixes for currently released app and a Swift 1.2 fork for development.

**Comment by vchoubard** [comment]
Anyone has a working fork ? @akolov ?

**Comment by jayisidoro** [comment]
i second that, does anyone have a working fork?

**Comment by vchoubard** [comment]
@jayisidoro try this one https://github.com/marcelofabri/HanekeSwift/tree/xcode-6.3 working fine

**Comment by akolov** [comment]
Sorry for the late reply, here's mine along with the crash fix: https://github.com/akolov/HanekeSwift/tree/swift-1.2

**Comment by hpique** [comment]
@nickoneill Put simply, life happened. The Swift 1.2 update should be up later today. Please follow progress on #151.
