### ISSUE TITLE
crash with NSLog() when using this string as first parameter

### ISSUE THREAD

**Issue by nevsi79** [Haneke/HanekeSwift#170]
![screenshot 2015-04-09 16 57 13](https://cloud.githubusercontent.com/assets/272277/7070940/1c01aa98-deda-11e4-95f7-442f109d7b4a.png)
http://stackoverflow.com/questions/26026570/swift-url-string-encoding-crashing-on-ios

workaround suggested: NSLog("Failed to update access date with error %@", error?.description ?? "")

**Comment by nevsi79** [comment]
Oh, I see this has been addressed in 8e659a3d9bcbcdb3fbe0080d60d9007de2406280 in November.

**Comment by hpique** [comment]
@nevsi79 Neat! Please let me know if the problem resurfaces.
