### ISSUE TITLE
swift 1.2 errors

### ISSUE THREAD

**Issue by yavuz** [Haneke/HanekeSwift#171]
swift 1.2 causes many errors

**Comment by mohsen1** [comment]
+1

**Comment by xiaoxiaocainiao** [comment]
+1

**Comment by CWadeCantley** [comment]
I just updated to the newest versions of xcode and yes... many many errors.  I working on cleaning it up so that I can use it but there are a couple gotchas that I don't fully understand.  Hopefully the author will jump on them.

**Comment by HerbstLukas** [comment]
I'm also working on getting it running with Swift 1.2, but currently I have 5 errors remaining :/ Hope that the author's will get an version ready :( +1

**Comment by yavuz** [comment]
may be, you can use it. temporarily :)
https://github.com/akolov/HanekeSwift/tree/swift-1.2

**Comment by shivateja** [comment]
+1

**Comment by hpique** [comment]
Duplicate of #151.

**Comment by KMKRN** [comment]
There is an issue with JSON data. Fetching JSON data from server seems to return one cached object which is not getting released. Cleaning Xcode cache did nothing.
