### ISSUE TITLE
More config options

### ISSUE THREAD

**Issue by sh00le** [Haneke/HanekeSwift#177]
Is it possible to add some kind of config for Haneke?
For example 
- cache validity period (in seconds)
- max disk usage (in MB)
- max memory usage (in MB)

**Comment by hpique** [comment]
Yes, these would be very nice additions to Haneke. Care to split them in separate issues so we can keep track of interest and progress?

**Comment by sh00le** [comment]
Like this?!

https://github.com/Haneke/HanekeSwift/issues/179
https://github.com/Haneke/HanekeSwift/issues/180
https://github.com/Haneke/HanekeSwift/issues/181

**Comment by hpique** [comment]
Perfect. Thanks!
