### ISSUE TITLE
After XCode upgrade there are many errors in code

### ISSUE THREAD

**Issue by Hextar** [Haneke/HanekeSwift#186]
HI, i bet the swift code syntax changed again. There are now errors like:

HanekeSwift-master/Haneke/UIButton+Haneke.swift:64:27: Use of unresolved identifier 'objc_getassociatedObject'

HanekeSwift-master/Haneke/NSFileManager+Haneke.swift:62:32: 'NSComparisonResult.Type' does not have a member named 'Orderedascending'

**Comment by tobiasoleary** [comment]
@hextar What version of Xcode and what version of the library are you using? 

Can you confirm this is fixed using the most recent version of the Xcode and the Library?

**Comment by dcharbonnier** [comment]
everything is fine with xcode 7.2
