### ISSUE TITLE
Getting EXC_BAD_INSTRUCTION sometimes while trying to fetch from cache

### ISSUE THREAD

**Issue by coryoso** [Haneke/HanekeSwift#192]
Sometimes the app gets an EXC_BAD_INSTRUCTION while trying to fetch a string from cache.
The cache fetching is done in a NSOperation subclass (with a maxConcurrentOperation of 10).
Console ouput says 
    malloc: *** error for object 0x7fb133c5d850: double free
    *** set a breakpoint in malloc_error_break to debug
I tried to set a breakpoint without success. Anything I did wrong?

**Comment by yurrriq** [comment]
:+1: I'm seeing this too.

**Comment by sman591** [comment]
+1 same issue

**Comment by Hxucaa** [comment]
same here. I've switched to SDWebImage since then.

**Comment by tobiasoleary** [comment]
+1

**Comment by tobiasoleary** [comment]
@sorncc Can you verify if this is the same issue as #115?

**Comment by sorncc** [comment]
I think it's the same issue

**Comment by yurrriq** [comment]
FWIW #115 looks like the same issue I'm having too.

**Comment by cmcnab** [comment]
+1

**Comment by qx** [comment]
+1 ALWAYS

**Comment by amnwebmaster** [comment]
+1

**Comment by hpique** [comment]
See #115.
