### ISSUE TITLE
Haneke crashing on setImage

### ISSUE THREAD

**Issue by petard** [Haneke/HanekeSwift#194]
I'm using Haenke to load images inside a collectionView in my custom cell class. I've manually added it to the project and have `import Haenke` in my custom class.

The custom cell class has the function `show product(p: Product)` which initializes the cell with the appropriate product information and also loading the product thumbnail:

```swift        

import Haneke

/* class setup code */

func showProduct(product: Product) {

/* setup code */

if let url = product.imageUrl {
            let u = NSURL(string: url)!
            self.thumbnail.hnk_setImageFromURL(u)
        }

} 
```

With this setup i get the following error message:
`dyld: Library not loaded: @rpath/Haneke.framework/Haneke
  Referenced from: /private/var/mobile/Containers/Bundle/Application/C15791E8-14ED-49BC-8459-B18299DBB25B/Discovery Demo.app/Discovery Demo
  Reason: image not found
(lldb)`

I'm a bit lost regarding the error message, not sure if this is a library loading issue or something else. The image url is correct as it's loading fine when loading it with Alamofire.

**Comment by petard** [comment]
Turns out this is a linking error as Haenke framework didn't get added to project properly. See also [this thread] (https://github.com/Alamofire/Alamofire/issues/101)

**Comment by mmmattos** [comment]
Glad this work-around worked for you too! ;)
