### ISSUE TITLE
No Such Module 'HanekeSwift'

### ISSUE THREAD

**Issue by jdssem** [Haneke/HanekeSwift#200]
I think it's very basic question. But I can't go further because of this problem.

I installed HanekeSwift through ```pod install``` and it was installed properly.
This is my Podfile

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'SwiftHTTP', '~> 0.9.4'
pod 'HanekeSwift'
```
In Xcode, pods are target dependencies normally.
![2015-06-05 13 30 49](https://cloud.githubusercontent.com/assets/978944/7999504/44c94038-0b87-11e5-868b-513479f59ed1.png)

When I ```import HanekeSwift``` in my view controller, 'No such module 'HanekeSwift' error occurs while another framework 'SwiftHTTP' works well.

I'm using Xcode 6.3.2.

How can I solve this problem?

**Comment by jdssem** [comment]
I'm not sure what I've done but now ```import Hanake``` works.

**Comment by Padarom** [comment]
We've had the same issue. I think at some point in my project I have made some wrong settings which resulted in my Unit Tests not being able to use CocoaPods (*perhaps this needs to be configured explicitly, anyways*). 

The class I tried to use `import Hanake` on had both my app, and my app's `Tests` in its target membership. Removing it from the `Tests` target made it work again.

**Comment by prabhupb** [comment]
@jdssem , most pod libraries use the same pod name as well as the module name, but the pod name for this library is HanekeSwift and the module name is Haneke. So *import Haneke* works while *import HanekeSwift* doesn't.

@Padarom , valid point. I have encountered such issues quite a few times which arises from the Tests target which I tend to overlook.

**Comment by lususvir** [comment]
I am still having this issue. I updated to Xcode 8.3.2 and Swift 3.1.1. When I `import Haneke` it says "No such module 'Haneke'".

**Comment by mortocks** [comment]
Same 

I updated to Xcode 8.3.2 and Swift 3.1.1. When I import Haneke it says "No such module 'Haneke'".

`xcodebuild -verbose`

`/Users/......./HeaderTableViewCell.swift:13:8: error: no such module 'Haneke'
import Haneke`

**Comment by viral105** [comment]
I am using Xcode Version 8.1 having the same issue. I tried both following.

import Haneke
import HanekeSwift

It is showing error No such module.
