### ISSUE TITLE
HanekeDemo collapse

### ISSUE THREAD

**Issue by wrhsan** [Haneke/HanekeSwift#204]
I don't know why this happening.  Device:  iPhone4S, System: iOS8.3 .  

Log:  dyld: Library not loaded: @rpath/Haneke.framework/Haneke
  Referenced from: /private/var/mobile/Containers/Bundle/Application/45BD1AE0-02B5-4D8D-BC2D-B849B3DFB058/HanekeDemo.app/HanekeDemo
  Reason: image not found

**Comment by meteochu** [comment]
Have you embedded the frameworks into the project yet?
More Info: http://stackoverflow.com/questions/24333981/ios-app-with-framework-crashed-on-device-dyld-library-not-loaded-xcode-6-beta

**Comment by wrhsan** [comment]
Thank you so much,it's worked.
