### ISSUE TITLE
Blink on UICollectionView reloadData with same data

### ISSUE THREAD

**Issue by Krizai** [Haneke/HanekeSwift#205]
In some cases blink of images in cells can be visible.
I suppose that it's because of using transitionWithView with 0 duration.
If i use success (self.imageView.image = image) to override this behaviour, there is no blink.

**Comment by sumitjain7** [comment]
Same happening with me

**Comment by thomascsorbamedia** [comment]
Same here

**Comment by sumitjain7** [comment]
I removed the code for reload data. Instead I am re-assigning the delegate to 'nil' and then to 'self'.
It worked for me and blinking resolved:)

**Comment by kapoorsahil** [comment]
@sumitjain7 Can you elaborate?

**Comment by Krizai** [comment]
Should be fixed after 5fff29f52a0a6e290934974b8270cf45044a2bd0

**Comment by tirrorex** [comment]
It is note, could you reopen the issue please?
