### ISSUE TITLE
Cache to disk w/o memory

### ISSUE THREAD

**Issue by rephiscorth** [Haneke/HanekeSwift#206]
I'm working with 200+ images loaded from network. I'm attempting to cache them, but sometimes I get OOM (which is expected because it's a lot of images). 

I'm using Shared.imageCache#fetch(URL:) for this operation, but I don't see any option to disable on-memory cache. Is this supported?

**Comment by raptox** [comment]
Please what was the answer? I need this.

My app crashes when the user scrolls through too many pictures ...
