### ISSUE TITLE
How to remove all fetched data

### ISSUE THREAD

**Issue by thomascsorbamedia** [Haneke/HanekeSwift#213]
Hi, i have a settings page in my app, here i would like to be able to press a button and then delete all fetched data from my device. This has to be key independent.
Anyone know a solution?

**Comment by streak22** [comment]
+1

**Comment by Huato115** [comment]
.remove

**Comment by dcharbonnier** [comment]
@thomascsorbamedia does https://github.com/Haneke/HanekeSwift/pull/267 fix your issue / answer your question ?

**Comment by thomascsorbamedia** [comment]
Yeah, thanks for help looking, found an other solutions that is more compliant with my needs.

**Comment by dcharbonnier** [comment]
Prefect!

**Comment by orkenstein** [comment]
@thomascsorbamedia 
Hi!
What was the solution? How to remove ALL data?

**Comment by thomascsorbamedia** [comment]
Hi @orkenstein , i stopped using hanekeSwift, to buggy for me. i use a background task to download all the images and other files. to delete them i created i function that deletes all the files within a specific directory in my app. However, the above solution did not work for me.
