### ISSUE TITLE
Clear Data of Cache

### ISSUE THREAD

**Issue by streak22** [Haneke/HanekeSwift#214]
Hi to All!   I was trying to probe the clear data and i write this code:

```swift
        let URL = NSURL(string: "http://www.laps4.com/juegos/imagen-de-Castlevania-Lords-of-Shadow-2-33677.jpg")!
        let cache = Haneke.Shared.imageCache
        let iconFormat = Format<UIImage>(name: "icons", diskCapacity: 10 * 1024 * 1024)
        cache.addFormat(iconFormat)
        cache.remove(key: "http://www.laps4.com/juegos/imagen-de-Castlevania-Lords-of-Shadow-2-33677.jpg", formatName: "icons")
        cache.removeAll()
        cache.fetch(URL: URL, formatName: "icons").onSuccess{image in
            self.imagen.image=image
        }.onFailure { error in
            println(error?.localizedDescription as String!)
        }
```

The first time that i start the app it download the image and delay 10 seconds. But the second time it doit automatic. (I had the remove and removeAll method call before)

What i am doing wrong? Or why the cache does not be delete in the start of the app?

Thank you very much!

**Comment by dcharbonnier** [comment]
@streak22 can you try https://github.com/Haneke/HanekeSwift/pull/267 and tell me if this solve your issue please ?

**Comment by dcharbonnier** [comment]
assuming #267 work
