### ISSUE TITLE
Allow placeholder to be cached if URL has no image

### ISSUE THREAD

**Issue by carbocation** [Haneke/HanekeSwift#215]
If the URL has no image (`imageView.hnk_setImageFromURL`), it's probably a broken image. These happen quite often on the internet. Rather than retrying every time, there should be a flag that permits us to say "if the image cannot be found, set the cached value to the placeholder image" which will stop trying to re-download all of the broken images on each load.

**Comment by ZAPHIT** [comment]
its already have placeholder.. i think this issue is close.

**Comment by hpique** [comment]
NSURLSession might be doing this already. If not, you can always subclass NetworkFetcher or implement your own with a different network policy.
