### ISSUE TITLE
Adding Support for Swift 2.0

### ISSUE THREAD

**Issue by kylry** [Haneke/HanekeSwift#217]
Maybe it's just me, but would be great if Haneke could support Swift 2.0. Getting many errors during installation.

**Comment by bradycoye** [comment]
This branch has is current with the latest beta syntax. https://github.com/meteochu/HanekeSwift.git

**Comment by eneko** [comment]
I was looking for Xcode 7 / Swift 2.0 pull requests and couldn't find any. Thanks for sharing.

**Comment by japarrado** [comment]
i try integrate this branch from pod:

pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'swift-2.0'

and i get this error: 
warning: Could not find remote branch swift-2.0 to clone.
fatal: Remote branch swift-2.0 not found in upstream origin

**Comment by eneko** [comment]
@japarrado I've been using this fork, works fine:

    pod 'HanekeSwift', :git => 'git@github.com:meteochu/HanekeSwift.git', :branch => 'swift-2.0'

**Comment by japarrado** [comment]
great with pod 'HanekeSwift', :git => 'https://github.com/meteochu/HanekeSwift.git', :branch => 'swift-2.0'

I try download this image but don't load :(
URL: http://files.parsetfss.com/933960fc-1c6a-4a1e-ba45-c535cd577bfc/tfss-fca604df-7b08-46e8-bf06-0ad13ce5bb65-008solomilloalaparrillaimage1x.jpg

**Comment by eneko** [comment]
@japarrado If you are using Xcode 7 with Swift 2.0, you are probably getting security errors for downloading images from non-https urls.  I believe the configuration changes you need are at the application level, not on the framework. Take a look at http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11

**Comment by japarrado** [comment]
i put info in info.plist but dont' work...i thinkg is a bug of xcode 7 beta 6 simulator

**Comment by rromanchuk** [comment]
Xcode7GM is out, this needs to be be merged into master

**Comment by keith** [comment]
Here's the PR for Swift 2.0 support https://github.com/Haneke/HanekeSwift/pull/221

**Comment by hpique** [comment]
Swift 2.0 support is now on master. Thanks to @meteochu for providing an alternative while this was unavailable.
