### ISSUE TITLE
Swift 2.0 -- Ton of errors :/

### ISSUE THREAD

**Issue by dustfire** [Haneke/HanekeSwift#222]
I am trying to convert the whole thing to Swift 2.0 for XCode7 -- any plans on your end?

**Comment by meteochu** [comment]
You can use my fork which is currently up to date with all Swift 2.0 Changes!
https://github.com/meteochu/HanekeSwift

**Comment by dustfire** [comment]
dude you rock, thanks! @meteochu

**Comment by psparago** [comment]
I'm not an XCode/CocoaPods expert (actually barely literate), so I'm hoping someone can help. Below is the console log when I try to 'pod install' this fork. Any ideas? I really want to avoid a manual installation if possible.

pod install
Updating local specs repositories

CocoaPods 0.39.0.beta.4 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Pre-downloading: `HanekeSwift` from `git@github.com:meteochu/HanekeSwift.git`, branch `swift-2.0`

[!] Error installing HanekeSwift
[!] /usr/bin/git clone git@github.com:meteochu/HanekeSwift.git /var/folders/9b/n4r60ss157501_9z95lk2f3m0000gn/T/d20150917-31414-vw3prn --single-branch --depth 1 --branch swift-2.0

Cloning into '/var/folders/9b/n4r60ss157501_9z95lk2f3m0000gn/T/d20150917-31414-vw3prn'...
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by sicaboy** [comment]
@meteochu Looks cool man, but is there any way to install from pods?

**Comment by mobinzk** [comment]
@sicaboy For now you can use the following pod request till it gets marge

```swift
pod "HanekeSwift", :git => "https://github.com/meteochu/HanekeSwift.git"
```

**Comment by yurrriq** [comment]
FWIW I'm doing as @mobinzk suggests, without issue.

**Comment by vbrazo** [comment]
+1

**Comment by hpique** [comment]
Swift 2.0 support is now on master. Thanks to @meteochu for providing an alternative while this was unavailable.
