### ISSUE TITLE
Is there anyway I can setup trusted host?

### ISSUE THREAD

**Issue by diprajak** [Haneke/HanekeSwift#227]

**Comment by dcharbonnier** [comment]
do you mean this https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/plist/info/NSAppTransportSecurity ?

**Comment by diprajak** [comment]
No. Alamofire gives you API to setup Trust policy. I was looking for same feature
https://github.com/Alamofire/Alamofire#security

**Comment by hpique** [comment]
@diprajak I would recommend for you to write your own fetcher using NetworkFetcher as a reference. See the readme for more info.
