### ISSUE TITLE
"Invalid redeclaration of 'JSON'" error when using SwifyJSON with project. 

### ISSUE THREAD

**Issue by levibostian** [Haneke/HanekeSwift#229]
My iOS Swift project includes [SwifyJSON](https://github.com/SwiftyJSON/SwiftyJSON) to parse JSON I download from my API easily. 

When I include HanekeSwift into my project, I get the error "Invalid redeclaration of 'JSON'" in my [SwifyJSON.swify file line 56](https://github.com/SwiftyJSON/SwiftyJSON/blob/master/Source/SwiftyJSON.swift#L56) as it declares a struct called JSON: 
```
public struct JSON {
    ...
}
``` 

and HanekeSwift [uses the name JSON as well](https://github.com/Haneke/HanekeSwift/blob/master/Haneke/Data.swift#L67) for an enum:
```
public enum JSON : DataConvertible, DataRepresentable {
    ...
}
```

The two are conflicting with each other. I use HanekeSwift for caching images specifically now but potentially other data later. I use SwifyJSON to parse JSON data coming back from my API that I download with Alamofire. So I don't see where I can remove the need for a library as they all have different needs.

Any workaround to this? Or will it require the need to rename JSON enum declaration in the library to avoid the conflict?

**Comment by levibostian** [comment]
This is also true for extension `NSFileManager` function:
```
func < (lhs: NSNumber, rhs: NSNumber) -> Bool {
    return lhs.compare(rhs) == NSComparisonResult.OrderedAscending
}
```
SwifyJSON has it's own version of this code:
```
public func <(lhs: NSNumber, rhs: NSNumber) -> Bool {
    
    switch (lhs.isBool, rhs.isBool) {
    case (false, true):
        return false
    case (true, false):
        return false
    default:
        return lhs.compare(rhs) == NSComparisonResult.OrderedAscending
    }
}
```

---

I already went through my code and change all `JSON` instances in HanekeSwift to `JSONData` and removed the function `<`, though it should be renamed. Compiles and works great.

**Comment by hpique** [comment]
Use fully qualified names. `Haneke.JSON`.

**Comment by levibostian** [comment]
I will not make a pull request at the moment, but I may in the future. SwiftyJSON is a popular library and so is Haneke. I will for sure be using both in future projects so using fully qualified names for Haneke would be great to resolve this issue again in the future. 

Thank you for the help!
