### ISSUE TITLE
setImagFromURL is not setting the image at all

### ISSUE THREAD

**Issue by MBLESSEN** [Haneke/HanekeSwift#233]
In swift 1.2 this code worked and set the images nothing has changed except im using swift 2.0 now.
The images are not displayed.

            let urlString = review.user!.image!
            let url = NSURL(string: urlString)
            vivrcell.userImage.hnk_setImageFromURL(url!)

**Comment by droideca** [comment]
I had the same problem, but it was due to a NSAppTransportSecurity problem. Check that just in case.

**Comment by ZAPHIT** [comment]
All haneke codes are working.. there might some problems on your code implementation.. the one your showing is just a snippet..

**Comment by jkosoy** [comment]
I think I'm seeing the same thing as well.

Example Code ::

```
        let url = NSURL(string: "https://placeholdit.imgix.net/~text?txtsize=33&txt=Screenshot&w=250&h=250")

        let imageView = UIImageView(frame: CGRect(x: 0, y: 0, width: 250, height: 250))

        imageView.hnk_setImageFromURL(url!, placeholder: nil, format: nil,
            failure: { _ in
            }, success: { _ in
                print("Image loaded") // prints out successfully
                print(imageView.image) // nil
            })
        
        addSubview(imageView)
```

**Comment by ZAPHIT** [comment]
@jkosoy  try removing format, also there is a problem with your closure.. read more about handling closures...

**Comment by dcharbonnier** [comment]
I don't think there is a bug here, ping me if I'm wrong I will reopen. thx
