### ISSUE TITLE
Manually install in xcode 7.0.1 and swift 2.0 does not work

### ISSUE THREAD

**Issue by imranshams** [Haneke/HanekeSwift#236]
Hi, Please see full detail error on:
http://stackoverflow.com/questions/33241713/swift-add-haneke-framework-to-xcode-7-0-1-not-work

**Comment by dcharbonnier** [comment]
I don't think there is a problem here, it's not the right way of including a framework. You should try https://github.com/Carthage/Carthage it make the process really easy
