### ISSUE TITLE
Example for Preloading

### ISSUE THREAD

**Issue by scisci** [Haneke/HanekeSwift#244]
In our app we'd like to preload a set of images before the imageviews are even ready. Is this possible with Haneke? If so, it'd be great to see an example of how this could be done. The fact that Haneke uses the dimensions of the imagview to cache the image makes me think that I'd have to also preload the image using those dimensions, is that right?

**Comment by docterd** [comment]
+ Vote Up. Especially in combination with the new Prefetching API for UICollectionView and UITableViews.

**Comment by patthehuman** [comment]
why did you close this without answering the question?
