### ISSUE TITLE
Cannot convert value of type error

### ISSUE THREAD

**Issue by tolgaytoklar** [Haneke/HanekeSwift#257]
Your example is giving compiler error:

        let URL = NSURL(string: "http://haneke.io/icon.png")!
        let fetcher = NetworkFetcher<UIImage>(URL: URL)
        cache.fetch(fetcher: fetcher).onSuccess { image in
            // Do something with image
        }

Cannot convert value of type 'NetworkFetcher<UIImage>' to expected argument type 'Fetcher<JSON>'

I am using with latest version of swift.

**Comment by poolqf** [comment]
Something like:
```swift
if let fetcher = NetworkFetcher<UIImage>(URL: URL) as? Fetcher<UIImage> {
    //WHATEVER
}
```

Does not work?

**Comment by tolgaytoklar** [comment]
No

http://prntscr.com/9h00bv

**Comment by hpique** [comment]
@tolgaytoklar According to the screenshot looks like you're trying to use a UIImage fetcher on a JSON cache, hence the error.
