### ISSUE TITLE
CFURLCreateStringByAddingPercentEscapes is deprecated

### ISSUE THREAD

**Issue by dcharbonnier** [Haneke/HanekeSwift#260]
```
Carthage/Checkouts/HanekeSwift/Haneke/String+Haneke.swift:18:27: warning: 'CFURLCreateStringByAddingPercentEscapes' was deprecated in tvOS 9.0: Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).
```

and this project is back ;-)

**Comment by hpique** [comment]
Um. `stringByAddingPercentEncodingWithAllowedCharacters` doesn't have a  `charactersToLeaveUnescaped` parameter. I think we should continue using CFURLCreateStringByAddingPercentEscapes for now, and possibly file a radar to request a true alternative.

**Comment by dcharbonnier** [comment]
So this is not a solution ? 
https://github.com/simonbs/HanekeSwift/commit/8cb3597efe1973d055d5a583aa051b9cc9ce1e1f

**Comment by hpique** [comment]
Sorry, I meant `legalURLCharactersToBeEscaped` instead of `charactersToLeaveUnescaped`. Will edit.

simonbs@8cb3597 escapes all characters (it probably doesn't pass the unit tests). I always intended escaped filenames to be human readable, to help with debugging.

**Comment by dcharbonnier** [comment]
```
filename = "-".join(filename.componentsSeparatedByCharactersInSet(NSCharacterSet.newlineCharacterSet()))
filename = "-".join(filename.componentsSeparatedByCharactersInSet(NSCharacterSet.illegalCharacterSet()))
filename = "-".join(filename.componentsSeparatedByCharactersInSet(NSCharacterSet.controlCharacterSet()))
filename = "-".join(filename.componentsSeparatedByString(":"))
filename = "-".join(filename.componentsSeparatedByString("/"))
```
http://stackoverflow.com/questions/6102333/what-characters-are-allowed-in-a-ios-file-name

**Comment by hpique** [comment]
Unfortunately the collision risk is not negligible (as it would be with a MD5 hash, for example). Similar file names with illegal characters are very likely to map to the same result. For example:

hello:/world > hello--world
hello/:world > hello--world

**Comment by dcharbonnier** [comment]
No collision and path readability.
The only non allowed character is NUL. Hard to believe but I can create a filename with a new line, my finder have a hard time displaying it but it work.

![image](https://cloud.githubusercontent.com/assets/6220422/12073279/8048022c-b0cb-11e5-9b42-f06d05641df1.png)

```

let map: [NSCharacterSet:String] = [
    NSCharacterSet(charactersInString: "%"):"%25",
    NSCharacterSet(charactersInString: "\0"):"%00",
    NSCharacterSet(charactersInString: ":"):"%3A",
    NSCharacterSet(charactersInString: "/"):"%2F"
]

for m in map {
    filename = filename.componentsSeparatedByCharactersInSet(m.0).joinWithSeparator(m.1)
}
```
