### ISSUE TITLE
When cells are scrolled off screen, will the image download request be cancelled?

### ISSUE THREAD

**Issue by joe528** [Haneke/HanekeSwift#274]
I am using HanekeSwift in a table view. When I scroll quickly, some cells are off screen and their images are not shown. Would the image network requests for these off-screen cells be cancelled automatically?

**Comment by hpique** [comment]
Hi @joe528. 

No. You can call `hnk_cancelSetImage` in `prepareForReuse`, for example.

**Comment by joe528** [comment]
Thanks. Now I call hnk_cancelSetImage() in prepareForReuse().

Is there any extra checking I should do?
