### ISSUE TITLE
conflict with SwiftyJSON

### ISSUE THREAD

**Issue by djdance** [Haneke/HanekeSwift#275]
this works in SwuftyJSON
```
var q=JSON([:])
```

and not work with Haneke added.
XCode says
**Cannot invoke 'JSON' with an argument list of type '([_ : _])'**

**Comment by djdance** [comment]
also redeclaration of func <

**Comment by hpique** [comment]
Hi @djdance. If you import both Haneke and SwiftyJSON, or anything else that defines a JSON type, you need to use fully qualified names (e.g., `Haneke.JSON`).

**Comment by djdance** [comment]
I do not use Haneke.JSON but it uses it itself somewhere. So I just commented 3 items

Data.swift: public enum JSON ...
Haneke.swift: public static var JSONCache...
NSFileManager+Haneke.swift: func < ...
