### ISSUE TITLE
Show a black line under iPhone6s Plus

### ISSUE THREAD

**Issue by mokai** [Haneke/HanekeSwift#278]
![41cceaca-feb7-4840-9955-ae394a086eb7](https://cloud.githubusercontent.com/assets/4702757/12669940/548334ec-c69f-11e5-97a9-368acede989e.png)
Like this，Under the other device to normal

**Comment by dcharbonnier** [comment]
can we see the related code ? this is most likely unrelated to haneke

**Comment by mokai** [comment]
@dcharbonnier 
self.imagesView.hnk_setImageFromURL(url, placeholder: nil)

**Comment by mokai** [comment]
The image link is http://rent.biketo.com/uploads/images/201601/20160126174610_lmwgh.jpg
