### ISSUE TITLE
What kind of settings can maximize UI scrolling performance?

### ISSUE THREAD

**Issue by joe528** [Haneke/HanekeSwift#283]
I have a table view where each cells have an image that will be downloaded via HanekeSwift.

There is a bit of jerkiness while the images are downloaded.

What kind of settings can be made in HanekeSwift to maximize UI scrolling performance?

**Comment by patricks** [comment]
+1

**Comment by zackshapiro** [comment]
+1

**Comment by aksh1t** [comment]
+1

**Comment by Fosile** [comment]
+1

**Comment by reinderdevries** [comment]
Easy. Use HanekeSwift to cache and/or download the image, and then use a custom format that resizes the image to fit the width and height of the table view cell's image view.

    imageView?.hnk_setImageFromURL(url, format: Format<UIImage>(name: "cell", diskCapacity: 10 * 1024 * 1024) { [weak imageView] image in
            return image.imageWithSize(imageView?.bounds.size)
    })

The method `imageWithSize(_:)` returns a cropped, scaled image. See https://github.com/Haneke/HanekeSwift/issues/373

Make sure to give the image view a solid background, set `opaque = true`, avoid blended layers, etc. to make sure the table view cells render fast.
