### ISSUE TITLE
Any chance of modifying this to work on OS X with NSImage?

### ISSUE THREAD

**Issue by brendand** [Haneke/HanekeSwift#314]
I am using your awesome library for my iOS app, but I would also like to use it in the OS X version of my app.

Any chance that it could return NSImages instead of UIImages when running on OS X?

**Comment by patthehuman** [comment]
Can't you just store the image as NSData?

**Comment by brendand** [comment]
Sure, but all the methods in this framework either accept or return UIImages. I guess I can fork it and see if I can change it to use something more generic which can then maybe have a macro setup which uses UIImage on iOS and NSImage on OS X.
