### ISSUE TITLE
Solution to Haneke fails on CGSizeZero UIImageView

### ISSUE THREAD

**Issue by drosenstark** [Haneke/HanekeSwift#317]
Haneke fails one of its asserts if you try to load using `hnk_setImageFromURL` when the `UIImageView` is size zero. This is my hack to deal with this:

``` swift
class UIImageViewWithDelayedLoad : UIImageView {
    var url : NSURL?

    init(urlForLoadWhenFrameNotZero: NSURL) {
        super.init(frame: CGRectZero)
        self.url = urlForLoadWhenFrameNotZero
    }

    required init?(coder: NSCoder) { super.init(coder: coder) }

    override func layoutSubviews() {
        super.layoutSubviews()

        guard let url = url else { return }
        guard (frame.size.width > 0 && frame.size.height > 0) else { return }
        self.hnk_setImageFromURL(url)
        self.url = nil
    }
}
```

Is this redundant with some functionality in Haneke? If not, possibly it's useful to somebody else... thanks!

**Comment by TosinAF** [comment]
Quick heads up

You can avoid all that with hnk_setImageFromURL(url, format: Format<UIImage>(name: "original"))

Using a standard format disables the resizing that leads to that crash when the imageView has no frame due to autolayout.

**Comment by drosenstark** [comment]
thanks!!! so, in your solution which image is cached? in my solution, is it both the original and the resized? thanks for this response!

**Comment by TosinAF** [comment]
Happy to help, so basically Format original, caches the original image, no resizing is done. 

If you wanted, you could pass in a custom format and the result of that is what is cached. 

let iconFormat = Format<UIImage>(name: "icons", diskCapacity: 10 * 1024 * 1024) { image in
    return imageByRoundingCornersOfImage(image)
}

**Comment by drosenstark** [comment]
So my class, though it was created in ignorance, could kind of make sense to cache the resized image, assuming that the frame gets set and changes to a non-zero size only once?
