### ISSUE TITLE
tvOS is not supported in CocoaPods

### ISSUE THREAD

**Issue by maxgorodivskyi** [Haneke/HanekeSwift#320]
Hello, today I've tried to include Haneke to my tvOS app through CocoaPods and Received 
![screen shot 2016-06-07 at 4 41 24 pm](https://cloud.githubusercontent.com/assets/18209424/15859712/e9b53cfa-2cce-11e6-8241-9623b19d5d58.png)
I've tried adding last version, same result
pod 'HanekeSwift', '~> 0.10.1’

However I was able to install AltHanekeSwift

**Comment by dcharbonnier** [comment]
I'm really encouraging you to use Carthage instead of cocoapods

**Comment by markltownsend** [comment]
Why use Carthage instead of Cocoapods? I don't see any advantage

**Comment by dcharbonnier** [comment]
The advantage for this issue is that hanekeswift is compatible, any commit is, out of the box.
Now I don't want to enter a troll ;-) there is plenty of carthage vs cocoapod articles on the web :-)

**Comment by chadmoone** [comment]
I understand that you're encouraging the use of Carthage, but as you stated, there are plenty of Carthage/CocoaPods articles on the web, and both sides are represented.  CocoaPods also has drastically higher adoption overall.

Are you implying that you don't intend to support CocoaPods for all platforms going forward?
