### ISSUE TITLE
Swift 3.0 Branch

### ISSUE THREAD

**Issue by jordanekay** [Haneke/HanekeSwift#323]
I'd like to make a pull request to add support for Swift 3.0 to SVGPath. Could you make a `swift/3.0` branch for me to merge into? Thanks!

**Comment by dcharbonnier** [comment]
thx https://github.com/Haneke/HanekeSwift/tree/feature/swift-3

**Comment by jamieomatthews** [comment]
@jordanekay whats your progress on this?  If you've already done this, no need to duplicate the work here.  Thanks!
