### ISSUE TITLE
Does Haneke support .svg format.

### ISSUE THREAD

**Issue by shrikantwalekar-tudip** [Haneke/HanekeSwift#330]
Hi, I am new to iOS and using this amazing library for getting images from url. I am facing a problem with fetching .svg image.
What I am doing is 
ImageView.hnk_setImageFromURL(imageUrl, placeholder: UIImage(named: "placeholder.jpg"))

I have verified the image url on browser.
What should I do ??

**Comment by shrikantwalekar-tudip** [comment]
Hi, really need help on this one !!

**Comment by dcharbonnier** [comment]
hi,
There is no svg support for ios, it's not related to haneke
