### ISSUE TITLE
Swift 2.3 support - branch missing?

### ISSUE THREAD

**Issue by alpennec** [Haneke/HanekeSwift#331]
Hello,
I can't find any branch for iOS Swift 2.3.
Is is possible to have one so we can start migrating Haneke Swift to Swift 2.3 (+ use it in our projects with Carthage and CocoaPods).
Thanks,
Axel

**Comment by alpennec** [comment]
Any update on this? The code needs to be updated to support Swift 2.3. Still having issues building the project.

**Comment by chadmoone** [comment]
@alpennec I'm guessing you just did the migration yourself (it's pretty minor), but if you are looking for a branch, you can point to the fork from the PR above for the time being. Hopefully with Xcode 8 GM coming in the next week or so, we can get an official branch set up here.

**Comment by ramesh-dev** [comment]
Guys, Xcode GM is out, any updates on Swift 2.3 branch?

**Comment by gblotter** [comment]
Also submitted a PR... w/ changes to the Travis-CI build setting AND to the OHHTTPStubs framework version to one that supports Swift 2.3 as well #344

**Comment by cannyboy** [comment]
I'm using this for 23 till it's on an official branch: https://github.com/cannyboy/HanekeSwift

Pod-cats can use:
`pod 'HanekeSwift', :git => 'https://github.com/cannyboy/HanekeSwift.git'`

**Comment by dcharbonnier** [comment]
Swift 3 done

**Comment by dcharbonnier** [comment]
https://github.com/Haneke/HanekeSwift/pull/350
