### ISSUE TITLE
Image scale does not match screen scale

### ISSUE THREAD

**Issue by Jiropole** [Haneke/HanekeSwift#341]
I've tried it a couple ways, currently using imageCache.fetch(url, formatName). I noticed my images were appearing too large, and when I inspect the image in onSuccess, noticed the image dimensions are 2x larger than they should be and scale was 1.0. I'm testing on a scale 2.0 screen so this is wrong. 

Is this by design, i.e. is the user expected recreate the image from the cache with the proper scale? Which isn't really feasible when using the convenience category functions like hnk_setImageFromUrl(). My format does use a custom transform, but it's just an ImageResizer and a little custom clipping. When my transform returns the image, it is the correct size and scale. 

It is also the correct size and scale the _first_ time it is returned from the cache, i.e. when newly minted. Does this sound like a bug (if so, pretty big), or like a newb doing something wrong...?

**Comment by Jiropole** [comment]
Found other notes around this, not sure if the solution(s) should have fixed this issue or if I'm still missing something. #160 #252 #281

**Comment by tirrorex** [comment]
Same thing here

**Comment by dcharbonnier** [comment]
duplicate #281
