### ISSUE TITLE
Swift 3 Release?

### ISSUE THREAD

**Issue by rlam3** [Haneke/HanekeSwift#346]
Swift 3 Release?

**Comment by lluisgerard** [comment]
I'm using the code from this PR https://github.com/Haneke/HanekeSwift/pull/338 and it's compiling. I cannot test/try it with my app because I have to make a lot of changes before 😱 

My Podfile has this at the moment:
```ruby
pod 'HanekeSwift', :git => 'https://github.com/jasonnoahchoi/HanekeSwift', :branch => 'swift3'
```

**Comment by 8masterofpuppets8** [comment]
Any idea when this will be merged in?

**Comment by okankocyigit** [comment]
@lluisgerard it's compiled and working for me.

**Comment by rlam3** [comment]
I think we need to update the documentation if swift 3.0 is updated.

**Comment by dcharbonnier** [comment]
right @rlam3 #349

**Comment by alpennec** [comment]
Strange to see that the last commit on master was done on Apr 21, 2016.
@rlam3 are you sure the master branch is using Swift 3? Or should se use the Swift 3 branch?

**Comment by dcharbonnier** [comment]
@alpennec right it's not on master for now, I'm updating to 2.3 and then I will check 3.0 but the branch 3.0 has been reported as "working"

**Comment by StupidDutchName** [comment]
I would like a HanekeSwift Swift 3 cocoapods release, since we're using it in one of our internal dependencies, and you can't specify a :git dependency through a podspec. which breaks our build.

Not having a swift 3 pod is a severe hindrance for bigger projects, please consider publishing a Release Candidate from your swift 3 branch that we could use.

**Comment by rlam3** [comment]
@alpennec Like @StupidDutchName said. It is becoming a hinderance for development projects not to have a swift 3 version of cocoapods. Hope to see a full release to the master branch soon! Thanks!

**Comment by StupidDutchName** [comment]
I cannot release an internal dependency because `pod spec lint` checks out dependencies based on the podspec file which cannot specify a :git parameter, and thus checks out the master branch / latest cocoapods release. This is a severe hindrance for us.
