### ISSUE TITLE
what time will be support swift3.0?

### ISSUE THREAD

**Issue by Mosaics** [Haneke/HanekeSwift#347]
And I have a question: I'm used "SwiftyJSON" in my project;
I noticed that you are using JSon cache like this:
********************
let cache = Cache<JSON>(name: "github")
let URL = NSURL(string: "https://api.github.com/users/haneke")!

cache.fetch(URL: URL).onSuccess { JSON in
    print(JSON.dictionary?["bio"])
}
****************
But you know,"SwiftyJSON" can be used to request to the data, it also has a JSON parsing method.
So, I want to use "SwiftyJSON" request results directly cache directly, rather than your's.
So，I used like this:
*************
 let cache = Shared.JSONCache
cache.Set(XXXX:XXXX,XXXX:XXXX)

But this cause an error: "JSon cannot covert JSon....",Maybe it mean your JSON parsing methods of objects, and "SwiftyJSON" parse out objects are not compatible.

I also used "typeAlis JSON = swiftyJSON.JSON" to distinguish between.

Any good solution here?

**Comment by dcharbonnier** [comment]
swift 3 should be supported for the rest I think you should post this question to stackoverflow you will get more answers then here
