### ISSUE TITLE
Swift 3 and Xcode 8

### ISSUE THREAD

**Issue by kforte318** [Haneke/HanekeSwift#348]
As I'm sure you're aware, Haneke isn't compatible with the new stuff yet. Hope it's ready to use again soon!

**Comment by dcharbonnier** [comment]
it's not documented (#349) but master is swift3

**Comment by alpennec** [comment]
Strange to see that the last commit on master was done on Apr 21, 2016.
@dcharbonnier are you sure the master branch is using Swift 3? Or should se use the Swift 3 branch?

**Comment by LadyDeveloper** [comment]
I have the same problem 
<img width="2417" alt="schermata 2016-09-19 alle 13 03 02" src="https://cloud.githubusercontent.com/assets/11472348/18629940/7508157a-7e69-11e6-925a-a26beef7409f.png">
How can I fix the problem?

**Comment by alejandrorbradford** [comment]
Is it working with Swift 3 or 2.3?

**Comment by kforte318** [comment]
I have the same issue as LadyDeveloper. I don't think it's on Swift 3...?

**Comment by andreyrd** [comment]
The branch [master](https://github.com/Haneke/HanekeSwift/tree/master) **is not** on Swift 3.
The branch [feature/swift-3](https://github.com/Haneke/HanekeSwift/tree/feature/swift-3) **is** on Swift 3.

If you use CocoaPods, you can use it with this line:
```pod "HanekeSwift", :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-3'```

**Comment by lauracpierre** [comment]
Any chance we can get this merged soon ? Thanks !

**Comment by muescha** [comment]
there is a pull request https://github.com/Haneke/HanekeSwift/pull/379

but this repo looks abandomned

**Comment by dcharbonnier** [comment]
there is someone to merge the PR but not to work on it, the first goal for a PR is to pass the tests #379 does not
