### ISSUE TITLE
a warning in swift3,please fix it

### ISSUE THREAD

**Issue by Mosaics** [Haneke/HanekeSwift#359]
i used this method:

cache.fetch(key: "funny-games.mp4").onSuccess { data in
    // Do something with data
}

it throw a warning:"Result of call to '. onSuccess' is ununsed " 

if i used it continue like this ：

cache.fetch(key: "funny-games.mp4").onSuccess { data in
    // Do something with data
}.onFailure { (error) in
  // Do something with error
}

it told me ：“Result of call to '. onFailure' is ununsed ”

how do I solve this problem?

**Comment by rytonbay** [comment]
Sorry if I'm missing something, but for me HanekeSwift won't build at all in Swift 3. Where is the working version?

**Comment by rytonbay** [comment]
Never mind my previous comment, I got it to work by having this in my podfile:
`pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift', :branch => 'feature/swift-3'`

**Comment by Mosaics** [comment]
@rytonbay  3Q

**Comment by dcharbonnier** [comment]
use the branch feature/swift-3
