### ISSUE TITLE
Is it a memory leak in image loading caused by Haneke?

### ISSUE THREAD

**Issue by peihsendoyle** [Haneke/HanekeSwift#362]
I'm dealing with images in TableView and CollectionView and using Haneke for caching. But I'm realize that everytime a cell is visible (with imageView inside), the memory grow dramatically. The Allocations Instrument indicate that there is "cg raster data" leak the memory.
<img width="1392" alt="screen shot 2016-10-18 at 12 59 41 am" src="https://cloud.githubusercontent.com/assets/7514128/19449052/463348d4-94ce-11e6-9e7d-c67969bdcfa2.png">
and inside it are many CoreGraphics algorithms:
<img width="1024" alt="screen shot 2016-10-18 at 1 00 58 am" src="https://cloud.githubusercontent.com/assets/7514128/19449111/763f575c-94ce-11e6-8c3a-db4799843fd2.png">

Here is my tableViewCell and tableView codes:
<img width="845" alt="screen shot 2016-10-18 at 1 02 51 am" src="https://cloud.githubusercontent.com/assets/7514128/19449159/a37e638e-94ce-11e6-9386-2f0928305a80.png">
<img width="832" alt="screen shot 2016-10-18 at 1 02 59 am" src="https://cloud.githubusercontent.com/assets/7514128/19449160/a37fdc6e-94ce-11e6-828b-cb6d2dbb3489.png">

Anyone can help me in this case, thanks very much.

**Comment by yoller** [comment]
Did u find any solution for this?

**Comment by peihsendoyle** [comment]
Dear yoller,

I found out that the things lead to problems is the size of image. If the size is too big, the device has to use their resources to process the image. That lead to an increasing in memory. I resize the image and the problem solved.

Thanks for your concern :)

**Comment by rlam3** [comment]
@peihsendoyle What was the size of the image files you are using? I believe I may be running into a similar issue.

**Comment by peihsendoyle** [comment]
@rlam3 sorry for the late reply.

Actually, I'm using IMGIX service to resize the image and detect face. It allows you to pass params like width, height, crop,... and return a new proper url instead of your directly url. 

The problem is that you have to use their url, it means you must store images resource in their repository. I don't realized it 3 months ago, and just used directly url, it leads to the image was not resize.

In my opinion, when you download an image and attach it to your imageView, it should have the size equivalent to the bounds of imageView (like 50x50, 70x70).
