### ISSUE TITLE
setImageFromURL returns error with only the word "accepted" in the userinfo

### ISSUE THREAD

**Issue by JarekToro** [Haneke/HanekeSwift#364]
**Other Info**

```
NSError?	domain: "io.haneke" - code: 18446744073709551214	0x000060000004c180
_userInfo	_TtGCs29_NativeDictionaryStorageOwnerCSo8NSObjectPs9AnyObject__ *	1 key/value pair	0x000060000006dec0
key	__NSCFConstantString *	"NSLocalizedDescription"	0x000000010936abb0
value	__NSCFConstantString *	"accepted"	0x0000000109ef20d0
```

Also im not the best debugger in the world but going back through the thread i was able to find the image data that it downloaded. So there doesn't seem to be an issue with the actual downloading of the image.

Thanks

**Comment by dcharbonnier** [comment]
debug your http request with a proxy like charlesproxy there is mos likely a problem at this level
