### ISSUE TITLE
How to use image in cache?

### ISSUE THREAD

**Issue by zhanswift** [Haneke/HanekeSwift#365]
How to use images in cache?

**Comment by PKrupa94** [comment]
First you can cache image directly using url or image with unique.

**cache image using url**
`imageView.hnk_setImageFromURL(url)`

**cache image with unique key**
`imageView.hnk_setImage(image, key: key)`

You can fetch cache images using `Shared.imageCache` and use this instance for fetch cache images.

create image cache instance
`let imageCache = Shared.imageCache`

**fetch cache image with url**
`imageCache.fetch(URL: <#T##NSURL#>).onSuccess { (image) in
      //set your image here
  }`

**fetch cache image with key**
` imageCache.fetch(key: "").onSuccess { (image) in
      //set your image here
   }`
