### ISSUE TITLE
Release Tag For Swift 2.3 Support?

### ISSUE THREAD

**Issue by brianmichel** [Haneke/HanekeSwift#372]
Hello, I was wondering if a tag can be published the with the current changes in `master` so that we can get Swift 2.3 support without having to point directly to a commit. It seems like the last tagged release was sometime in January.

**Comment by che1404** [comment]
Hi @brianmichel , I'm trying to locate that exact commit (Swift 2.3 support). Do you know which one would it be?

Thanks!

**Comment by egosapien** [comment]
I just came across this too. The feature branch was deleted after merging. I went ahead and created a tag "v0.10.2" for swift 2.3 support on a fork. May be useful until this issue gets addressed.

Commit hash for swift 2.3 is "8ff1c5c"

https://github.com/reppanetgmbh/HanekeSwift/releases/tag/v0.10.2

**Comment by dcharbonnier** [comment]
the master branch is now swift-3
