### ISSUE TITLE
How should one set round corners when dealing with image?

### ISSUE THREAD

**Issue by rlam3** [Haneke/HanekeSwift#373]
Looking at the documentation, what should iconFormat look like? I'm a bit confused...

I'm trying to apply round corner layer onto the fetched image. Would this be applied after the image was set onto the iboutlet? 

```swift
imageView.hnk_setImageFromURL(url, format: iconFormat)
/// So change image after it has been set? 
```

Reference:

http://www.appcoda.com/ios-programming-circular-image-calayer/

**Comment by reinderdevries** [comment]
Don't use CALayer, because it'll dynamically round the edges of the image view. If you want to cache the rounding effect, you need to work with the bitmap data. Try this:

    let iconFormat = Format<UIImage>(name: "icon_30", diskCapacity: 25 * 1024 * 1024) { image in
        return image.imageWithSize(CGSize(width: 30, height: 30), andCornerRadius: 15.0)
    }

    imageView.hnk_setImageFromURL(url, format: iconFormat)

And the UIImage extension:

    extension UIImage
    {
        func imageWithSize(_ size:CGSize, andCornerRadius radius:CGFloat = 0.0) -> UIImage
        {
            var scaledImageRect = CGRect.zero;
            
            let aspectWidth:CGFloat = size.width / self.size.width;
            let aspectHeight:CGFloat = size.height / self.size.height;
            let aspectRatio:CGFloat = max(aspectWidth, aspectHeight);
            
            scaledImageRect.size.width = self.size.width * aspectRatio;
            scaledImageRect.size.height = self.size.height * aspectRatio;
            scaledImageRect.origin.x = (size.width - scaledImageRect.size.width) / 2.0;
            scaledImageRect.origin.y = (size.height - scaledImageRect.size.height) / 2.0;
            
            let rect = CGRect(x: 0, y: 0, width: size.width, height: size.height);
            
            UIGraphicsBeginImageContextWithOptions(size, true, 0);
            
            defer {
                UIGraphicsEndImageContext();
            }
            
            UIColor.white.set();
            UIRectFill(rect);
            
            if radius > 0
            {
                UIBezierPath(roundedRect: rect, cornerRadius: radius).addClip();
            }
            
            self.draw(in: scaledImageRect);
            
            let scaledImage = UIGraphicsGetImageFromCurrentImageContext();
            
            if  let data    = UIImageJPEGRepresentation(scaledImage!, 0.5),
                let image   = UIImage(data: data)
            {
                return image;
            }
            else
            {
                return scaledImage!;
            }
        }
    }
