### ISSUE TITLE
Swift 3 upgrade error...

### ISSUE THREAD

**Issue by rlam3** [Haneke/HanekeSwift#374]
Got the following for a swift 3 migration upgrade for haneke swift... was wondering how to resolve this. Thanks!

```swift

Analyzing dependencies
Pre-downloading: `HanekeSwift` from `https://github.com/Haneke/HanekeSwift/tree/feature/swift-3`

[!] Error installing HanekeSwift
[!] /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git clone https://github.com/Haneke/HanekeSwift/tree/feature/swift-3 /var/folders/3_/s_7hqrn93rz07b_4rtq0_c6r0000gp/T/d20161122-65725-c3x8io --template= --single-branch --depth 1

Cloning into '/var/folders/3_/s_7hqrn93rz07b_4rtq0_c6r0000gp/T/d20161122-65725-c3x8io'...
fatal: repository 'https://github.com/Haneke/HanekeSwift/tree/feature/swift-3/' not found

```

**Comment by jaimeagudo** [comment]
Your log doesn't look right to me @rlam3, check your Podfile syntax, mine works with

```pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-3'```

**Comment by rlam3** [comment]
@jaimeagudo is hanekeswift going to support swift 3 in the master branch soon? It's been a while since we got a refresh on the swift 3 branch. Thanks!

**Comment by StupidDutchName** [comment]
Anyone out there still using Swift 2?? Would really be nice to merge the Swift 3 branch!

**Comment by MaG21** [comment]
Well, I am. But using Swift 2 at this point in time is painful, no playground and xcode is not helping either.

**Comment by rlam3** [comment]
I switched over to kingfisher because the supported swift 3.

**Comment by 0xc00010ff** [comment]
Bump for merging `feature/swift-3`, but also note that you can use the Objective-C library with Swift 3 if you just want to pod install and move along. https://github.com/Haneke/Haneke

**Comment by dcharbonnier** [comment]
the master branch is now swift-3
