### ISSUE TITLE
carthage update error haneke

### ISSUE THREAD

**Issue by reshadf** [Haneke/HanekeSwift#376]
I am trying to get my project dependencies updated with Carthage. Unfortunately I am getting the following:  any ideas what to do?

>*** Building scheme "Haneke" in Haneke.xcworkspace
--- xcodebuild: WARNING: Unable to open project file '/Users/username/xcode/trials/Carthage/Checkouts/HanekeSwift/Haneke.playground' in workspace '/Users/username/xcode/trials/Carthage/Checkouts/HanekeSwift/Haneke.xcworkspace'.
** CLEAN FAILED **

>The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

>The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/username/xcode/trials/Carthage/Checkouts/HanekeSwift/Haneke.xcworkspace -scheme Haneke -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
--- xcodebuild: WARNING: Unable to open project file '/Users/username/xcode/trials/Carthage/Checkouts/HanekeSwift/Haneke.playground' in workspace '/Users/username/xcode/trials/Carthage/Checkouts/HanekeSwift/Haneke.xcworkspace'.
** CLEAN FAILED **

>The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

>The following build commands failed:
	Check dependencies
(1 failure)

**Comment by rgal75** [comment]
I am getting the same error and thus cannot build my project. Running
```
xcodebuild -workspace /Users/xxx/myproject/Carthage/Checkouts/HanekeSwift/Haneke.xcworkspace -scheme Haneke -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean
```
reveals the following:
```
=== CLEAN TARGET Haneke OF PROJECT Haneke WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by dcharbonnier** [comment]
you probably used at that time the wrong branch, the master branch is now swift-3
