### ISSUE TITLE
How to clear Haneke memory cache effectively on iOS?

### ISSUE THREAD

**Issue by vinios** [Haneke/HanekeSwift#378]
Main memory cache is bloating as user requests more number of images. As user session progresses, main memory size increases which applies excess pressure on memory. This is causing out of memory exception.

**Comment by vexy** [comment]
Can you tell how many images/requests are causing this issue ?

**Comment by vinios** [comment]
We are loading thumbnails in tableview cells. So After around 50-60 requests, memory allocation reach to 150MB.
