### ISSUE TITLE
Support for Version 8.3 (8E162)?

### ISSUE THREAD

**Issue by rlam3** [Haneke/HanekeSwift#387]
Support for Version 8.3 (8E162)?

A few new errors occured with XCode Version upgrade. New release, please.

Thank you!

![screen shot 2017-03-31 at 2 31 19 pm](https://cloud.githubusercontent.com/assets/1154044/24566339/bdebcdf2-161e-11e7-9a62-53ccaa114570.png)

**Comment by imroca** [comment]
I'm getting this error, i dont know for sure if it's related or not.

A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/ignacio/Mobile/Maka/Pin/Carthage/Checkouts/HanekeSwift/Haneke.xcworkspace -scheme Haneke -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
--- xcodebuild: WARNING: Unable to open project file '/Users/ignacio/Mobile/Maka/Pin/Carthage/Checkouts/HanekeSwift/Haneke.playground' in workspace '/Users/ignacio/Mobile/Maka/Pin/Carthage/Checkouts/HanekeSwift/Haneke.xcworkspace'.
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

**Comment by CodeSensei** [comment]
Can you pls provide an estimated date release for Swift 3 version?

**Comment by rlam3** [comment]
Merged but still hasn't been released... Any Updates? Thanks

**Comment by dcharbonnier** [comment]
the master branch is now swift-3
