### ISSUE TITLE
Updated pod repo for swift 3?

### ISSUE THREAD

**Issue by buiminhhuy** [Haneke/HanekeSwift#397]
Would you like to update pod repo for the library? Please help me this.

**Comment by cbess** [comment]
I'd also like them to update the podspec. 
I assume they want you to use the git repos directly in your Podfile:
```ruby
pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :commit => '694d6df'
```

**Comment by dcharbonnier** [comment]
cocoa pod is not supported
