### ISSUE TITLE
May 2017, Cannot build with carthage? (or anything?)

### ISSUE THREAD

**Issue by smhk** [Haneke/HanekeSwift#399]
Very sadly this excellent project seems to be dead ?

```
$ cat /var/folders/xh/m9fl5v8j4hv5mpt6pc85tjz80000gn/T/carthage-xcodebuild.r92iz1.log
/usr/bin/xcrun xcodebuild -workspace../Carthage/Checkouts/HanekeSwift/Haneke.xcworkspace -scheme Haneke -configuration Release -derivedDataPath ../Library/Caches/org.carthage.CarthageKit/DerivedData/HanekeSwift/v0.10.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildUser defaults from command line:
    IDEDerivedDataPathOverride = ../Library/Caches/org.carthage.CarthageKit/DerivedData/HanekeSwift/v0.10.1

Build settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos10.3

--- xcodebuild: WARNING: Unable to open project file ../ios/Carthage/Checkouts/HanekeSwift/Haneke.playground' in workspace '../ios/Carthage/Checkouts/HanekeSwift/Haneke.xcworkspace'.
=== CLEAN TARGET Haneke OF PROJECT Haneke WITH CONFIGURATION Release ===

Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
=== BUILD TARGET Haneke OF PROJECT Haneke WITH CONFIGURATION Release ===

Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **

```

**Comment by smhk** [comment]
Nobody else noticed this woe?

**Comment by jeannustre** [comment]
Same issue here. Manually opening the Haneke workspace Carthage checks out brings up an army of warnings and errors related to Swift conversion. I also tried to explicitly set the 'Swift Language Version' key in the Build Settings, but no luck there either.

I managed to get a working version of the framework by doing the following : 

1. Clone into the master branch
2. Open Haneke.xcodeproj
3. Build your target (Haneke-iOS for me) 
4. In the project explorer, right-click on Products/Haneke.framework -> Reveal in Finder
5. Copy the Haneke.framework from here to your Carthage/Build/<platform> folder
6. Manually link the .framework file to your project, the same way you would do after your Carthage install

This doesn't resolve the Carthage issue and should not be considered long-term solution, but it will do the trick until this is resolved.

**Comment by smhk** [comment]
Thanks for that Jean.  That's actually a good workaround, I'll do that too.

(At the moment I do it as described at https://github.com/Haneke/HanekeSwift under Installation/**Manually:**, but that is not ideal.)

Good thinking thanks.

**Comment by jeannustre** [comment]
So it seems that my workaround above will do the job when working with the Simulator, but will not build on an actual device. 
The "Manual" install works fine.

**Comment by smhk** [comment]
ah, luckily I did not try it yet!  :)
thanks for that tip - excellent.
I sure hope someone can fix the Carthage package ... that would be tops.

**Comment by SirWellington** [comment]
So it looks like this library is not actually updated for Swift 3.0, at least not according to the latest checkout I performed.

**Comment by lastcc** [comment]
Really nice lib but not compile with Carthage, Xcode 9 beta 6.

Command used in terminal: `carthage update --platform iOS`

*** Building scheme "Haneke" in Haneke.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/cc/Library/Mobile\ Documents/com~apple~CloudDocs/cc/2/KirinoX/Carthage/Checkouts/HanekeSwift/Haneke.xcworkspace -scheme Haneke -configuration Release -derivedDataPath /Users/cc/Library/Caches/org.carthage.CarthageKit/DerivedData/HanekeSwift/v0.10.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build (launched in /Users/cc/Library/Mobile Documents/com~apple~CloudDocs/cc/2/KirinoX/Carthage/Checkouts/HanekeSwift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/q5/96syyldx0cvgxsdjszdgpwgr0000gn/T/carthage-xcodebuild.rmxk4Z.log

**Comment by dcharbonnier** [comment]
the branhc swift-3 should be ok but now that there is swift-4, waiting for a PR with a build passing for swift-4
