### ISSUE TITLE
Swift 3 compatibility - Swift Compiler error Xcode 8.3.2

### ISSUE THREAD

**Issue by cristinaITdeveloper** [Haneke/HanekeSwift#402]
I added the library with pod, but Xcode reports many errors.

<img width="995" alt="schermata 2017-05-21 alle 22 44 30" src="https://cloud.githubusercontent.com/assets/11472348/26287220/1be8e0ea-3e77-11e7-8c56-6e084c576994.png">

**Comment by vikash1307** [comment]
Tried to download the source file and replace these files and it will work . I think some problem with cocoa pod link.

**Comment by jdam68** [comment]
Same issue here, for the moment I solved using the feature branch:

pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift', :branch => 'feature/swift-3'

It seems like master has been merged into brench, not the other way.

**Comment by strawberrycode** [comment]
+1

**Comment by EdenShapiro** [comment]
You also need to use `import Haneke` instead of `import HanekeSwift` at the top of your files

**Comment by cristinaITdeveloper** [comment]
I still have the same problem with Swift 3 and I have to import it like this 
pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift', :branch => 'feature/swift-3' 
as jdam68 wrote.

**Comment by dcharbonnier** [comment]
the @jdam68 solution should work
