### ISSUE TITLE
CLEAN FAILED with Swift 3

### ISSUE THREAD

**Issue by EijiPon** [Haneke/HanekeSwift#409]
=== CLEAN TARGET Haneke OF PROJECT Haneke WITH CONFIGURATION Release ===

Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
=== BUILD TARGET Haneke OF PROJECT Haneke WITH CONFIGURATION Release ===

**Comment by dcharbonnier** [comment]
use the feature branch for swift-3
