### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by MarcoFilosi** [Haneke/HanekeSwift#420]
Last release `0.10.1` has been created on 2 Jan 2016.

In the meantime master has been moved to Swift 3 and there are no releases of it.
We need to reference to `master` branch or `feature/swift-3` branch if we want to use this pod on XCode project.

Could you please consider to create a new release containing current master status?

Thanks

**Comment by randomiser** [comment]
Agreed. Would be good to get some of the PRs merged and this project updated.

**Comment by dcharbonnier** [comment]
no PR with a build passing is pending except one that is a design decision
