### ISSUE TITLE
When to release swift4.0 version of the code

### ISSUE THREAD

**Issue by BeckWang0912** [Haneke/HanekeSwift#424]
When to release swift4.0 version of the code？

**Comment by dcharbonnier** [comment]
https://github.com/Haneke/HanekeSwift/releases/tag/0.11.0

**Comment by Nautiyalsachin** [comment]
Please reopen this issue as its taking 0.10.0 as by default when I install it. I tried to update it manually, by forcefully giving 0.11.0, It gave me error. Thank you!
