### ISSUE TITLE
CocoaPods, not downloading last version 1.1

### ISSUE THREAD

**Issue by fermoya** [Haneke/HanekeSwift#426]
Hi,

I'd like to ask about the pod 'HanekeSwift', it downloads the latest that's in Cocoapods which is version 0.10.1 released in Jan 2016!!
https://cocoapods.org/pods/HanekeSwift

But in your codspec I see the latest version is 1.1:
https://github.com/Haneke/HanekeSwift/blob/master/HanekeSwift.podspec

Are you planning to release an official new version? So far I'm addressing this pod like:
pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'master'

I read Haneke wasn't going to support Swift 4 and wasn't being maintained but I see that's simply not true, you keep working on it, commits 18 days ago. Please let me know if I'm wrong, I really like this framework but also wanna keep updated with Swift 4.

Thanks in advance

**Comment by dcharbonnier** [comment]
Sorry cocoa pod is not and won't be anyone supported maybe you can use a git url with a tag with it or switch to Carthage

**Comment by smhk** [comment]
@fermoya , if you have not used Carthage yet, it is incredibly easier than using pods.

Hope it helps anyway!

**Comment by fermoya** [comment]
Thanks a lot for the prompt answer, I'll give it a thought and propose it to the rest of the team :D
