### ISSUE TITLE
Update Cocoapods Specs Repo

### ISSUE THREAD

**Issue by xrelative** [Haneke/HanekeSwift#428]
Can you please add version 0.11.0 to CocoaPods Specs Repo? 🙂

**Comment by smhk** [comment]
This is purely one man's opinion! ..

- cocoapods is far too much work to maintain
- cocoapods is on the "last days" .. as soon as SPM works, cocoapods will be history
- carthage is trivial to use, if you use pods you can convert to carthage in a minute
- carthage is far easier for the developer of Haneke (or other libraries) to maintain

Haneke is an amazing library,
- it is a huge amount of work to support Haneke
- maybe, it is best to forget about cocoapods support

Again just one man's opinion!  Good luck all !

**Comment by xrelative** [comment]
Thanks for your suggest @smhk, I think you right, I changed to Carthage.

Greetings!

**Comment by dcharbonnier** [comment]
Thanks @smhk
