### ISSUE TITLE
File path URL

### ISSUE THREAD

**Issue by drewg233** [Haneke/HanekeSwift#455]
Is there a way to obtain the file path url from a key? In my case I actually need the file URL and not just the data.

Something like:
```
let path = cache.path(forKey: "KEYHERE")
```

**Comment by eimermusic** [comment]
Maybe this still applies?
https://github.com/Haneke/HanekeSwift/issues/385

It is a hack though and not the safest thing in the world. There is no guarantee that the file will actually be cached already of that it won't be removed suddenly.

This is what I use when I absolutely need this (hello AVPlayer). This was modified from code someone shared a long time ago, either here or on SO I'd imagine. I am using a fork of Haneke so the following might not be 100% usable in regular Haneke.

```
    func filePath() -> URL {
        var path = URL(string: DiskCache.basePath())!
        path = path.appendingPathComponent("my_folder_name_that_wont_work_for_you/original")
        let cached = DiskCache(path: path.absoluteString).path(forKey: url.absoluteString)
        let fileUrl = URL(fileURLWithPath: cached)
        return fileUrl
    }
```
