### ISSUE TITLE
Why a frame is mandatory when using Haneke with UIImageView?

### ISSUE THREAD

**Issue by hopiaw** [Haneke/HanekeSwift#95]
Hi Hermes,

I was wondering why your library check by default the bounds of the image view and resize it to its size.

When using constraints (with visual format language), that's a problem cause I want to be able to declare my image view as following:

``` swift
self.imageView = UIImageView()
```

Constraints will then set the frame when layout will be applied.

Why not simply not resizing the image downloaded if no bounds? If that case is actually possible with your library, could you show me how with an example please.

Many thanks!
Teddy

Edit 1:

The error I encounter is the following:
assertion failed: [ hnk_format]: UImageView size is zero. Set its frame, call sizeToFit or force layout first

Answer:

The answer seems to be using the branch feature/uikit/format and pass a custom when calling hnk_setImageFromURL() method. For example below Format has its transform closure simply returning its input:

``` swift
Format<UIImage>("CustomCache", diskCapacity: 20 * 1024 * 1024, transform:{
            return $0
        })
```

Please let me know if there is a better solution for that.

Thanks!

**Comment by TosinAF** [comment]
Can i update the readme with this? I feel like docs on this is essential.
